// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversidadEF.Context;

#nullable disable

namespace UniversidadEF.Migrations
{
    [DbContext(typeof(UniversidadContext))]
    [Migration("20230817234444_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniversidadEf.Models.Alumno", b =>
                {
                    b.Property<Guid>("AlumnoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AlumnoDocumento")
                        .HasColumnType("int");

                    b.HasKey("AlumnoId");

                    b.HasIndex("AlumnoDocumento")
                        .IsUnique();

                    b.ToTable("Alumno", (string)null);

                    b.HasData(
                        new
                        {
                            AlumnoId = new Guid("5131973e-a517-4c5a-91d5-d2be6d4bac32"),
                            AlumnoDocumento = 1021669017
                        });
                });

            modelBuilder.Entity("UniversidadEf.Models.AlumnoAsignatura", b =>
                {
                    b.Property<Guid>("AlumnoAsignaturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlumnoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AsignaturaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Semestre")
                        .HasColumnType("int");

                    b.HasKey("AlumnoAsignaturaId");

                    b.HasIndex("AlumnoId");

                    b.HasIndex("AsignaturaId");

                    b.ToTable("AlumnoAsignatura", (string)null);

                    b.HasData(
                        new
                        {
                            AlumnoAsignaturaId = new Guid("2524e251-0885-4c16-b636-0f5616c59a06"),
                            AlumnoId = new Guid("5131973e-a517-4c5a-91d5-d2be6d4bac32"),
                            AsignaturaId = new Guid("ac3fc016-ade0-4772-92a3-85a61121878d"),
                            Semestre = 3
                        });
                });

            modelBuilder.Entity("UniversidadEf.Models.Asignatura", b =>
                {
                    b.Property<Guid>("AsignaturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AsignaturaCreditos")
                        .HasColumnType("int");

                    b.Property<string>("AsignaturaNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CarreraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProfesorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AsignaturaId");

                    b.HasIndex("CarreraId");

                    b.HasIndex("ProfesorId");

                    b.ToTable("Asignatura", (string)null);

                    b.HasData(
                        new
                        {
                            AsignaturaId = new Guid("ac3fc016-ade0-4772-92a3-85a61121878d"),
                            AsignaturaCreditos = 3,
                            AsignaturaNombre = "Programación Orientada a Objetos",
                            CarreraId = new Guid("40d1e0cd-e84c-4011-947e-58173a596bc8"),
                            ProfesorId = new Guid("920e874c-9eec-4c08-9507-485a9175b31c")
                        });
                });

            modelBuilder.Entity("UniversidadEf.Models.Carrera", b =>
                {
                    b.Property<Guid>("CarreraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CarreraNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("FacultadId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CarreraId");

                    b.HasIndex("FacultadId");

                    b.ToTable("Carrera", (string)null);

                    b.HasData(
                        new
                        {
                            CarreraId = new Guid("40d1e0cd-e84c-4011-947e-58173a596bc8"),
                            CarreraNombre = "Ingeniería de Software",
                            FacultadId = new Guid("a461d44b-14b6-4284-bc57-2270af9d8d85")
                        });
                });

            modelBuilder.Entity("UniversidadEf.Models.Facultad", b =>
                {
                    b.Property<Guid>("FacultadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FacultadNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FacultadId");

                    b.ToTable("Facultad", (string)null);

                    b.HasData(
                        new
                        {
                            FacultadId = new Guid("a461d44b-14b6-4284-bc57-2270af9d8d85"),
                            FacultadNombre = "Facultad de Ingeniería de Sistemas"
                        });
                });

            modelBuilder.Entity("UniversidadEf.Models.Persona", b =>
                {
                    b.Property<int>("PersonaDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonaDocumento"));

                    b.Property<string>("PersonaApellido")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PersonaCiudad")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PersonaCorreo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PersonaFechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<string>("PersonaGenero")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("PersonaNombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PersonaTelefono")
                        .HasColumnType("int");

                    b.HasKey("PersonaDocumento");

                    b.ToTable("Persona", (string)null);

                    b.HasData(
                        new
                        {
                            PersonaDocumento = 1921874154,
                            PersonaApellido = "Rojas",
                            PersonaCiudad = "Bogotá",
                            PersonaCorreo = "srojas@uan.edu.co",
                            PersonaFechaNacimiento = new DateTime(2005, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PersonaGenero = "M",
                            PersonaNombre = "Santiago",
                            PersonaTelefono = 300900400
                        },
                        new
                        {
                            PersonaDocumento = 58132098,
                            PersonaApellido = "Martinez",
                            PersonaCiudad = "Bogotá",
                            PersonaCorreo = "jcmartinezd@uan.edu.co",
                            PersonaFechaNacimiento = new DateTime(1976, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PersonaGenero = "M",
                            PersonaNombre = "Juan",
                            PersonaTelefono = 300900401
                        },
                        new
                        {
                            PersonaDocumento = 78234085,
                            PersonaApellido = "Sarmiento",
                            PersonaCiudad = "Bogotá",
                            PersonaCorreo = "asarmiento@uan.edu.co",
                            PersonaFechaNacimiento = new DateTime(1976, 10, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PersonaGenero = "F",
                            PersonaNombre = "Andrea",
                            PersonaTelefono = 300900402
                        });
                });

            modelBuilder.Entity("UniversidadEf.Models.Profesor", b =>
                {
                    b.Property<Guid>("ProfesorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ProfesorDocumento")
                        .HasColumnType("int");

                    b.HasKey("ProfesorId");

                    b.HasIndex("ProfesorDocumento")
                        .IsUnique();

                    b.ToTable("Profesor", (string)null);

                    b.HasData(
                        new
                        {
                            ProfesorId = new Guid("920e874c-9eec-4c08-9507-485a9175b31c"),
                            ProfesorDocumento = 58132098
                        });
                });

            modelBuilder.Entity("UniversidadEf.Models.Rector", b =>
                {
                    b.Property<Guid>("RectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RectorDocumento")
                        .HasColumnType("int");

                    b.HasKey("RectorId");

                    b.HasIndex("RectorDocumento")
                        .IsUnique();

                    b.ToTable("Rector", (string)null);

                    b.HasData(
                        new
                        {
                            RectorId = new Guid("531d2123-2836-4720-8d15-313c4aeda145"),
                            RectorDocumento = 78234085
                        });
                });

            modelBuilder.Entity("UniversidadEf.Models.Sede", b =>
                {
                    b.Property<Guid>("SedeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RectorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SedeDireccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SedeNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SedeId");

                    b.HasIndex("RectorId")
                        .IsUnique();

                    b.ToTable("Sede", (string)null);

                    b.HasData(
                        new
                        {
                            SedeId = new Guid("7b82b004-1f75-4226-8b91-f7d68b2534ea"),
                            RectorId = new Guid("531d2123-2836-4720-8d15-313c4aeda145"),
                            SedeDireccion = "CARRERA 38 #58A-77",
                            SedeNombre = "Sede Sur"
                        });
                });

            modelBuilder.Entity("UniversidadEf.Models.Alumno", b =>
                {
                    b.HasOne("UniversidadEf.Models.Persona", "Persona")
                        .WithOne("Alumno")
                        .HasForeignKey("UniversidadEf.Models.Alumno", "AlumnoDocumento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("UniversidadEf.Models.AlumnoAsignatura", b =>
                {
                    b.HasOne("UniversidadEf.Models.Alumno", "Alumno")
                        .WithMany("AlumnoAsignaturas")
                        .HasForeignKey("AlumnoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UniversidadEf.Models.Asignatura", "Asignatura")
                        .WithMany("AlumnoAsignaturas")
                        .HasForeignKey("AsignaturaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Alumno");

                    b.Navigation("Asignatura");
                });

            modelBuilder.Entity("UniversidadEf.Models.Asignatura", b =>
                {
                    b.HasOne("UniversidadEf.Models.Carrera", "Carrera")
                        .WithMany("Asignaturas")
                        .HasForeignKey("CarreraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniversidadEf.Models.Profesor", "Profesor")
                        .WithMany("Asignaturas")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrera");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("UniversidadEf.Models.Carrera", b =>
                {
                    b.HasOne("UniversidadEf.Models.Facultad", "Facultad")
                        .WithMany("Carreras")
                        .HasForeignKey("FacultadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Facultad");
                });

            modelBuilder.Entity("UniversidadEf.Models.Profesor", b =>
                {
                    b.HasOne("UniversidadEf.Models.Persona", "Persona")
                        .WithOne("Profesor")
                        .HasForeignKey("UniversidadEf.Models.Profesor", "ProfesorDocumento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("UniversidadEf.Models.Rector", b =>
                {
                    b.HasOne("UniversidadEf.Models.Persona", "Persona")
                        .WithOne("Rector")
                        .HasForeignKey("UniversidadEf.Models.Rector", "RectorDocumento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("UniversidadEf.Models.Sede", b =>
                {
                    b.HasOne("UniversidadEf.Models.Rector", "Rector")
                        .WithOne("Sede")
                        .HasForeignKey("UniversidadEf.Models.Sede", "RectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rector");
                });

            modelBuilder.Entity("UniversidadEf.Models.Alumno", b =>
                {
                    b.Navigation("AlumnoAsignaturas");
                });

            modelBuilder.Entity("UniversidadEf.Models.Asignatura", b =>
                {
                    b.Navigation("AlumnoAsignaturas");
                });

            modelBuilder.Entity("UniversidadEf.Models.Carrera", b =>
                {
                    b.Navigation("Asignaturas");
                });

            modelBuilder.Entity("UniversidadEf.Models.Facultad", b =>
                {
                    b.Navigation("Carreras");
                });

            modelBuilder.Entity("UniversidadEf.Models.Persona", b =>
                {
                    b.Navigation("Alumno")
                        .IsRequired();

                    b.Navigation("Profesor")
                        .IsRequired();

                    b.Navigation("Rector")
                        .IsRequired();
                });

            modelBuilder.Entity("UniversidadEf.Models.Profesor", b =>
                {
                    b.Navigation("Asignaturas");
                });

            modelBuilder.Entity("UniversidadEf.Models.Rector", b =>
                {
                    b.Navigation("Sede")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
